# Site settings
title: More than Smalltalk
#email: mail@ronalddehaan.nl
description: > # this means to ignore newlines until "baseurl:"
    Coding and theme by Ronald de Haan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ronalddehaan.nl" # the base hostname & protocol for your site
twitter_username:  tactic78
github_username:   tactic
linkedin_username: ronalddehaan78
untapped_username: ronald1978

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
