# Site settings
title: More than Smalltalk
email: mail@ronalddehaan.nl
description: > # this means to ignore newlines until "baseurl:"
    ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ronalddehaan.nl" # the base hostname & protocol for your site
twitter_username: tactic78
github_username:  tactic

# Build settings
markdown: kramdown
